# Generated by Django 4.2.7 on 2024-11-03 21:24

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viloyatname", models.CharField(max_length=255)),
                ("total_area", models.CharField(max_length=50)),
                ("cultivated_area", models.CharField(max_length=50)),
                ("forest_area", models.CharField(max_length=50)),
                ("wasteland_area", models.CharField(max_length=50)),
                ("pastures_area", models.CharField(max_length=50)),
                ("other_agricultural_land", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(upload_to="news_images/")),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("text", django_quill.fields.QuillField()),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("links", models.URLField(blank=True, null=True)),
                ("pictures", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="basic_app.post",
                    ),
                ),
            ],
        ),
    ]
